export const opstine = [
  { name: "Bihać", code: "003", canton: "Unsko-sanski kanton" },
  {
    name: "Bosanska Krupa",
    code: "008",
    canton: "Unsko-sanski kanton",
  },
  {
    name: "Bosanski Petrovac",
    code: "011",
    canton: "Unsko-sanski kanton",
  },
  { name: "Cazin", code: "019", canton: "Unsko-sanski kanton" },
  { name: "Ključ", code: "048", canton: "Unsko-sanski kanton" },
  { name: "Sanski Most", code: "076", canton: "Unsko-sanski kanton" },
  {
    name: "Velika Kladuša",
    code: "097",
    canton: "Unsko-sanski kanton",
  },
  { name: "Bužim", code: "124", canton: "Unsko-sanski kanton" },
  { name: "Orašje", code: "068", canton: "Posavski kanton" },
  { name: "Odžak", code: "066", canton: "Posavski kanton" },
  { name: "Domaljevac-Šamac", code: "012", canton: "Posavski kanton" },
  { name: "Banovići", code: "001", canton: "Tuzlanski kanton" },
  { name: "Gračanica", code: "035", canton: "Tuzlanski kanton" },
  { name: "Gradačac", code: "036", canton: "Tuzlanski kanton" },
  { name: "Kalesija", code: "044", canton: "Tuzlanski kanton" },
  { name: "Kladanj", code: "047", canton: "Tuzlanski kanton" },
  { name: "Čelić", code: "056", canton: "Tuzlanski kanton" },
  { name: "Lukavac", code: "057", canton: "Tuzlanski kanton" },
  { name: "Srebrenik", code: "085", canton: "Tuzlanski kanton" },
  { name: "Tuzla", code: "094", canton: "Tuzlanski kanton" },
  { name: "Živinice", code: "106", canton: "Tuzlanski kanton" },
  { name: "Doboj-Istok", code: "128", canton: "Tuzlanski kanton" },
  { name: "Sapna", code: "138", canton: "Tuzlanski kanton" },
  { name: "Teočak", code: "142", canton: "Tuzlanski kanton" },
  { name: "Breza", code: "016", canton: "Zeničko-dobojski kanton" },
  { name: "Kakanj", code: "043", canton: "Zeničko-dobojski kanton" },
  { name: "Maglaj", code: "060", canton: "Zeničko-dobojski kanton" },
  { name: "Olovo", code: "067", canton: "Zeničko-dobojski kanton" },
  { name: "Tešanj", code: "090", canton: "Zeničko-dobojski kanton" },
  { name: "Vareš", code: "096", canton: "Zeničko-dobojski kanton" },
  { name: "Visoko", code: "098", canton: "Zeničko-dobojski kanton" },
  { name: "Zavidović", code: "102", canton: "Zeničko-dobojski kanton" },
  { name: "Zenica", code: "103", canton: "Zeničko-dobojski kanton" },
  { name: "Žepče", code: "105", canton: "Zeničko-dobojski kanton" },
  { name: "Doboj-Jug", code: "132", canton: "Zeničko-dobojski kanton" },
  { name: "Usora", code: "025", canton: "Zeničko-dobojski kanton" },
  {
    name: "Goražde",
    code: "033",
    canton: "Bosansko-podrinjski kanton Goražde",
  },
  {
    name: "Foča",
    code: "134",
    canton: "Bosansko-podrinjski kanton Goražde",
  },
  {
    name: "Pale",
    code: "136",
    canton: "Bosansko-podrinjski kanton Goražde",
  },
  { name: "Bugojno", code: "017", canton: "Srednjobosanski kanton" },
  { name: "Busovača", code: "018", canton: "Srednjobosanski kanton" },
  {
    name: "Donji Vakuf",
    code: "026",
    canton: "Srednjobosanski kanton",
  },
  { name: "Dobrezići", code: "050", canton: "Srednjobosanski kanton" },
  { name: "Fojnica", code: "030", canton: "Srednjobosanski kanton" },
  {
    name: "Gornji Vakuf",
    code: "034",
    canton: "Srednjobosanski kanton",
  },
  { name: "Jajce", code: "042", canton: "Srednjobosanski kanton" },
  { name: "Kiseljak", code: "046", canton: "Srednjobosanski kanton" },
  { name: "Krešev", code: "051", canton: "Srednjobosanski kanton" },
  {
    name: "Novi Travnik",
    code: "065",
    canton: "Srednjobosanski kanton",
  },
  { name: "Travnik", code: "091", canton: "Srednjobosanski kanton" },
  { name: "Vitez", code: "100", canton: "Srednjobosanski kanton" },
  {
    name: "Čapljina",
    code: "021",
    canton: "Hercegovačko-neretvanski kanton",
  },
  {
    name: "Čitluk",
    code: "023",
    canton: "Hercegovačko-neretvanski kanton",
  },
  {
    name: "Grad Mostar",
    code: "180",
    canton: "Hercegovačko-neretvanski kanton",
  },
  {
    name: "Jablanica",
    code: "041",
    canton: "Hercegovačko-neretvanski kanton",
  },
  {
    name: "Konjic",
    code: "049",
    canton: "Hercegovačko-neretvanski kanton",
  },
  {
    name: "Neum",
    code: "107",
    canton: "Hercegovačko-neretvanski kanton",
  },
  {
    name: "Prozor-Rama",
    code: "073",
    canton: "Hercegovačko-neretvanski kanton",
  },
  {
    name: "Ravno",
    code: "207",
    canton: "Hercegovačko-neretvanski kanton",
  },
  {
    name: "Stolac",
    code: "086",
    canton: "Hercegovačko-neretvanski kanton",
  },
  {
    name: "Široki Brijeg",
    code: "054",
    canton: "Zapadnohercegovački kanton",
  },
  { name: "Grude", code: "037", canton: "Zapadnohercegovački kanton" },
  {
    name: "Ljubuški",
    code: "059",
    canton: "Zapadnohercegovački kanton",
  },
  {
    name: "Posušje",
    code: "070",
    canton: "Zapadnohercegovački kanton",
  },
  { name: "Hadžići", code: "038", canton: "Kanton Sarajevo" },
  { name: "Ilijaš", code: "040", canton: "Kanton Sarajevo" },
  { name: "Centar", code: "077", canton: "Kanton Sarajevo" },
  { name: "Ilidža", code: "078", canton: "Kanton Sarajevo" },
  { name: "Novo Sarajevo", code: "079", canton: "Kanton Sarajevo" },
  { name: "Vogošća", code: "080", canton: "Kanton Sarajevo" },
  { name: "Novi Grad", code: "108", canton: "Kanton Sarajevo" },
  { name: "Stari Grad", code: "109", canton: "Kanton Sarajevo" },
  { name: "Trnovo", code: "093", canton: "Kanton Sarajevo" },
  { name: "Livno", code: "055", canton: "Kanton 10" },
  { name: "Tomislavgrad", code: "028", canton: "Kanton 10" },
  { name: "Kupres", code: "052", canton: "Kanton 10" },
  { name: "Glamoč", code: "032", canton: "Kanton 10" },
  { name: "Bosansko Grahovo", code: "013", canton: "Kanton 10" },
  { name: "Drvar", code: "027", canton: "Kanton 10" },
];
